### ISSUE TITLE
HTML niet correct

### ISSUE THREAD

**Issue by KrijnHoetmer** [JesperHonders/accesDemo#5]
Heb je je HTML al eens door https://html5.validator.nu/ gehaald? Volgens mij gaan geneste `<a>` elementen namelijk niet helemaal lekker..

**Comment by BaardMoeder** [comment]
Hier heb je helemaal gelijk in. Niet aan gedacht.

Ik heb de Anchors verplaatst, en verdere HTML foutjes opgeschoond

**Comment by KoopReynders** [comment]
done
