### ISSUE TITLE
Wat gebeurt er in IE8 met je rem units?

### ISSUE THREAD

**Issue by KrijnHoetmer** [JesperHonders/accesDemo#6]
Je gebruikt op een aantal plekken de `rem` unit in je CSS, maar wat gebeurt er als deze niet ondersteund wordt, bijvoorbeeld in IE8? Test je demo op meer verschillende platformen en browsers ajb.

**Comment by BaardMoeder** [comment]
Ik heb de CSS herschreven nu zonder Flex en Relative units.

**Comment by KoopReynders** [comment]
PE gaat er ook over dat je best vooruitstrevende technieken zoals Flex of Relative Units kan gebruiken, maar dat je een werkmethode toepast die ondervangt wat er gebeurt als een browser het niet ondersteunt. 
Dus ... feature detection?

**Comment by KoopReynders** [comment]
done
