### ISSUE TITLE
Waarom content.json?

### ISSUE THREAD

**Issue by KrijnHoetmer** [JesperHonders/accesDemo#7]
Waar heb je content.json voor nodig, als alle data in principe ook al in je HTML staat? Is het niet handiger om je HTML juist te hergebruiken op de plek waar je nu een aparte file inlaadt? In dat geval wordt je HTML namelijk je 'API' (die je sowieso al nodig hebt). Heb je naar deze oplossing gekeken, en wat waren hier de voor- en nadelen van, waardoor je bij content.json kwam?

**Comment by BaardMoeder** [comment]
Ja daar heb je gelijk in, maar ik heb hier wel degelijk naar gekeken. Echter is het onmogelijk om html op te slaan in de localstorage om deze vervolgens weer te gebruiken als HTML, zoals uitgelegd bij de Demo die ik gaf tijdens de eind beoordeling. Wat ik wel zou kunnen doen is alle content binnen de html tags op te slaan in de localstorage. Echter dit zorgt ervoor dat er gigantisch veel keys worden aangemaakt binnen de storage, om deze weer appart binnen tags te kunnen renderen.

**Comment by KoopReynders** [comment]
done
